### PR TITLE
Hopefully fix ext not working (assuming subfolder setup) + some cleanup

### PR DESCRIPTION
**Pull request by dsevillamartin**
**Fixes hopefully #17**

**Changes proposed in this pull request:**
- I'm assuming the ext did not work with subfolders due to the register path check
  - Please check whether it did/didn't work, and whether this PR fixes it if necessary
- JS cleanup
  - Use Flarum prettier
  - Add Flarum tsconfig
  - Update to Webpack 5

**Reviewers should focus on:**
- Mainly the register path thing on subfolder setups

**Confirmed**

- [X] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by ekumanov** [comment]
Is there a way I can test this merge request on my forum before it is merged?

**Comment by dsevillamartin** [comment]
@ekumanov Yep! You can run `composer require fof/stopforumspam:dev-ds/fixes-cleanup`.

**Comment by ekumanov** [comment]
@datitisev thanks, just tested it and can confirm it finally works now, thank you! When you release it, how should I switch to the released version (from the dev branch, although they will be the same as content)?

**Comment by dsevillamartin** [comment]
@ekumanov Looks like `composer require fof/stopforumspam` will upgrade from dev to stable. So you can run that when it's released - I'll ping you and let you know 🙂.

**Pull request merged**
